version: "3.8"
services:
  scraper:
    build: ./scraper/
    depends_on:
      - db
    links:
      - db
  api:
    build: ./api/
    depends_on:
      - db
    links:
      - db
    ports:
      - "8081:8081"
  fe:
    build: ./fe/
    depends_on:
      - api
    links:
      - api
    ports:
      - "8080:80"
  db:
    build: ./database/
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
